# Generated by Django 3.2 on 2021-04-18 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='課題名')),
                ('comment', models.TextField(blank=True, max_length=100, verbose_name='コメント')),
                ('stat', models.IntegerField(default=0, verbose_name='進捗状況')),
                ('stat_max', models.IntegerField(default=1, verbose_name='最大進捗')),
                ('deadline', models.DateTimeField(verbose_name='期限日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記録日時')),
            ],
        ),
    ]
